# Generated by Django 5.1 on 2025-01-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0026_complaint_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fish', 'Fish'), ('food', 'Fish Food'), ('plants', 'Aquatic Plants')], default='fish', max_length=20),
        ),
    ]
