# Generated by Django 5.1 on 2025-01-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0031_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishWaterPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=100, unique=True)),
                ('min_ph', models.FloatField()),
                ('max_ph', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('hardness', models.CharField(choices=[('soft', 'Soft'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50)),
            ],
        ),
    ]
