# Generated by Django 5.1 on 2025-01-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0032_fishwaterpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishwaterpreferences',
            name='description',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fishwaterpreferences',
            name='hardness',
            field=models.CharField(choices=[('soft', 'Soft'), ('medium', 'Medium'), ('hard', 'Hard'), ('soft_to_medium', 'Soft to Medium'), ('medium_to_hard', 'Medium to Hard')], max_length=50),
        ),
    ]
