# Generated by Django 5.1 on 2025-02-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0033_fishwaterpreferences_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCareGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=255, unique=True)),
                ('maintenance', models.TextField()),
                ('feeding_habits', models.TextField()),
                ('water_quality', models.TextField()),
                ('additional_tips', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish_care_images/')),
            ],
        ),
    ]
