# Generated by Django 5.1 on 2025-02-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0034_fishcareguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('tank_requirements', models.TextField()),
                ('diet', models.TextField()),
                ('compatibility', models.TextField()),
                ('common_diseases', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish_care_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='FishCareGuide',
        ),
    ]
