# Generated by Django 5.1 on 2025-02-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0035_fishcare_delete_fishcareguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCareGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('feeding_habits', models.TextField()),
                ('water_quality', models.TextField()),
                ('fish_image', models.ImageField(upload_to='fish_images/')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
