# Generated by Django 5.1 on 2025-02-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0038_order_delivery_person_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='pin_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
