# Generated by Django 5.1 on 2025-03-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0040_deliveryperson_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_person',
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
    ]
