# Generated by Django 5.1 on 2025-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0042_deliveryperson_order_delivery_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
