# Generated by Django 5.1 on 2025-03-13 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0043_alter_deliveryperson_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='delivery_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_person_status', to='aquaapp.order'),
        ),
    ]
